### ISSUE TITLE
remove kibana related files

### ISSUE THREAD

**Issue by gillyb** [gillyb/sensitive#1]

**Comment by rgl** [comment]
May I ask why you want to do this? Wouldn't it be better to just follow upstream without changing the code too much? That would be easier to update Sense, I guess. At most you [could disable kibana](https://www.elastic.co/guide/en/sense/current/installing.html#disable_discover).

**Comment by gillyb** [comment]
well, the original reason I thought of doing this was to make the release package smaller. But you're right, there's not really a point in doing this...
